
enum.ui.scene = {}
enum.ui.scene.login = "loginScene"
enum.ui.scene.test = "testScene"
enum.ui.scene.battle = "battleScene"
enum.ui.scene.world = "worldScene"
enum.ui.scene.versionUpdate = "versionUpdateScene"
enum.ui.scene.dock = "dockScene"
enum.ui.scene.popup = "popupScene"
enum.ui.scene.top = "topScene"
enum.ui.scene.ArtEditor = "ArtEditorScene" --资源选择界面

enum.ui.layer = {}
enum.ui.layer.gm = "gm"
enum.ui.layer.profile = "profile"
enum.ui.layer.protocol = "protocol"
enum.ui.layer.registerLogin = "registerLogin"
enum.ui.layer.sdkLogin = "sdkLogin"
enum.ui.layer.deviceInfo = "deviceInfo"
enum.ui.layer.battleDock = "battleDock"
enum.ui.layer.worldDock = "battleDock"
enum.ui.layer.consoleTab = "consoleTab"
enum.ui.layer.mainMenu = "mainMenu"
enum.ui.layer.joystick = "joystick"
enum.ui.layer.taskBrief = "taskBrief"
enum.ui.layer.versionUpdate = "versionUpdate"
enum.ui.layer.noticeBoard = "noticeBoard"
enum.ui.layer.battle = "battle"
enum.ui.layer.battleHp = "battleHp"
enum.ui.layer.messagebox = "messagebox"
enum.ui.layer.tips = "tips"
enum.ui.layer.effect = "effect"
enum.ui.layer.mask = "mask"
enum.ui.layer.touch = "touch"
enum.ui.layer.loading = "loading"
enum.ui.layer.dialog = "dialog"
enum.ui.layer.reconnect = "reconnect"
enum.ui.layer.audio = "audio"
enum.ui.layer.transition = "transition"

enum.ui.layer.request = "request"
enum.ui.layer.response = "response"
enum.ui.layer.print = "printLayer"
enum.ui.layer.chat = "chat" --聊天
enum.ui.layer.selectServer = "select"
enum.ui.layer.createPlayer = "create"
enum.ui.layer.selectPlayer = "select"

-- enum.ui.layer.tab = {}
-- enum.ui.layer.tab.gm = "gm"

enum.ui.layer.activityTab = "activityTab"
enum.ui.layer.activity = {}
enum.ui.layer.activity.duanwu = "activity_duanwu"
enum.ui.layer.activity.zhongqiu = "activity_zhongqiu"

enum.ui.layer.test = "test"
enum.ui.layer.testMenu = "testMenu"
enum.ui.layer.testBehaviourUpdate = "Behaviour Update"
enum.ui.layer.testBehaviourTouch = "Behaviour Touch"
enum.ui.layer.testCombineMeshes = "Combine Mesh"
enum.ui.layer.testPool = "Pool And Particles"
enum.ui.layer.testNetwork = "Network"
enum.ui.layer.testShader = "Shader"
enum.ui.layer.testTab = "Tab Layer"
enum.ui.layer.testLocailzation = "Locailzation"
enum.ui.layer.testAvatar = "Avatar"
enum.ui.layer.testBitmap = "Bitmap Font"
enum.ui.layer.testMask = "Mask"
enum.ui.layer.testTransition = "Transition"
enum.ui.layer.testQuality = "Quality"
enum.ui.layer.testSpritePacker = "SpritePacker"
enum.ui.layer.testNativeBridge = "NativeBridge"
enum.ui.layer.testBackgroundDownload = "BackgroundDownload"
enum.ui.layer.testSdk = "Sdk"
enum.ui.layer.testFastScroll = "Fast Scroll"
enum.ui.layer.testAudio = "Audio"
enum.ui.layer.testScreenshot = "ScreenShot"

enum.ui.view = {}
enum.ui.view.test = "Test"
enum.ui.view.battle = "Battle"
enum.ui.view.world = "World"

-- enum.ui.layer.testClose = "testClose"
